# -*- coding: utf-8 -*-
"""Numpy Data Exploler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ynjuar0Y-WveWRC3HJTlm3Eq8bRHWoN

# IMPORT MODULE
"""

import numpy as np
import time

"""# SECTION 1: ARRAY CREATION, INDEXING, AND SLICING

## Array Creation
"""

# 1D Array
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"1D Array:\n{arr_1d}")
print(f"Shape: {arr_1d.shape}, Dimensions: {arr_1d.ndim}, Size: {arr_1d.size}\n")

# 2D Array
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print(f"2D Array:\n{arr_2d}")
print(f"Shape: {arr_2d.shape}, Dimensions: {arr_2d.ndim}, Size: {arr_2d.size}\n")

# 3D Array
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print(f"3D Array:\n{arr_3d}")
print(f"Shape: {arr_3d.shape}, Dimensions: {arr_3d.ndim}, Size: {arr_3d.size}\n")

# Special Arrays
zeros_arr = np.zeros((3, 4))
ones_arr = np.ones((2, 3, 4))
identity_arr = np.eye(4)
range_arr = np.arange(0, 20, 2)
linspace_arr = np.linspace(0, 10, 5)
random_arr = np.random.randint(1, 100, size=(4, 5))

print(f"Zeros Array (3x4):\n{zeros_arr}\n")
print(f"Identity Matrix (4x4):\n{identity_arr}\n")
print(f"Range Array (0 to 20, step 2):\n{range_arr}\n")
print(f"Linspace Array (0 to 10, 5 points):\n{linspace_arr}\n")
print(f"Random Array (4x5, values 1-99):\n{random_arr}\n")

"""## Indexing"""

print("\n1.2 Indexing Operations:")
print(f"Original 2D Array:\n{arr_2d}\n")
print(f"Element at [1, 2]: {arr_2d[1, 2]}")
print(f"First row: {arr_2d[0]}")
print(f"Last column: {arr_2d[:, -1]}")
print(f"Element at [-1, -1]: {arr_2d[-1, -1]}\n")

"""## Slicing"""

print(f"Original 1D Array: {arr_1d}")
print(f"Elements [2:7]: {arr_1d[2:7]}")
print(f"Every 2nd element: {arr_1d[::2]}")
print(f"Reversed array: {arr_1d[::-1]}\n")

print(f"Original 2D Array:\n{arr_2d}")
print(f"\nFirst 2 rows, first 3 columns:\n{arr_2d[:2, :3]}")
print(f"\nEvery other row:\n{arr_2d[::2, :]}")
print(f"\nLast 2 rows, last 2 columns:\n{arr_2d[-2:, -2:]}\n")

# Boolean Indexing
mask = random_arr > 50
print(f"Boolean Mask (values > 50):\n{mask}")
print(f"Filtered values: {random_arr[mask]}\n")

"""# SECTION 2: MATHEMATICAL, AXIS-WISE, AND STATISTICAL OPERATIONS

"""

# Create sample dataset for analysis
np.random.seed(42)
sales_data = np.random.randint(100, 1000, size=(12, 4))  # 12 months, 4 products
print(f"\nSample Dataset - Monthly Sales Data (12 months x 4 products):\n{sales_data}\n")

arr_a = np.array([10, 20, 30, 40, 50])
arr_b = np.array([1, 2, 3, 4, 5])

print(f"Array A: {arr_a}")
print(f"Array B: {arr_b}")
print(f"Addition (A + B): {arr_a + arr_b}")
print(f"Subtraction (A - B): {arr_a - arr_b}")
print(f"Multiplication (A * B): {arr_a * arr_b}")
print(f"Division (A / B): {arr_a / arr_b}")
print(f"Power (A ** 2): {arr_a ** 2}")
print(f"Square Root: {np.sqrt(arr_a)}")
print(f"Exponential: {np.exp(arr_b)}")
print(f"Logarithm: {np.log(arr_a)}\n")

# 2.2 Axis-wise Operations
print("\n2.2 Axis-wise Operations on Sales Data:")
print("-" * 40)

monthly_total = np.sum(sales_data, axis=1)  # Sum across products (axis=1)
product_total = np.sum(sales_data, axis=0)  # Sum across months (axis=0)

print(f"Monthly Total Sales (sum across products):\n{monthly_total}\n")
print(f"Product Total Sales (sum across months):\n{product_total}\n")

monthly_avg = np.mean(sales_data, axis=1)
product_avg = np.mean(sales_data, axis=0)

print(f"Monthly Average Sales:\n{monthly_avg}\n")
print(f"Product Average Sales:\n{product_avg}\n")

# 2.3 Statistical Operations
print("\n2.3 Statistical Analysis:")
print("-" * 40)

print(f"Overall Statistics:")
print(f"  Total Sales: {np.sum(sales_data)}")
print(f"  Mean: {np.mean(sales_data):.2f}")
print(f"  Median: {np.median(sales_data):.2f}")
print(f"  Standard Deviation: {np.std(sales_data):.2f}")
print(f"  Variance: {np.var(sales_data):.2f}")
print(f"  Min Value: {np.min(sales_data)}")
print(f"  Max Value: {np.max(sales_data)}")
print(f"  25th Percentile: {np.percentile(sales_data, 25):.2f}")
print(f"  75th Percentile: {np.percentile(sales_data, 75):.2f}\n")

# Product-wise statistics
print(f"Product-wise Statistics:")
for i in range(sales_data.shape[1]):
    print(f"  Product {i+1}: Mean={np.mean(sales_data[:, i]):.2f}, "
          f"Std={np.std(sales_data[:, i]):.2f}, "
          f"Min={np.min(sales_data[:, i])}, "
          f"Max={np.max(sales_data[:, i])}")

# Correlation matrix
correlation_matrix = np.corrcoef(sales_data.T)
print(f"\nCorrelation Matrix between Products:\n{correlation_matrix}\n")

# Cumulative operations
cumulative_sales = np.cumsum(sales_data, axis=0)
print(f"Cumulative Sales (first 3 months):\n{cumulative_sales[:3]}\n")

"""# SECTION 3: RESHAPING AND BROADCASTING TECHNIQUES

"""

# 3.1 Reshaping Operations
print("\n3.1 Reshaping Operations:")
print("-" * 40)

original = np.arange(1, 25)
print(f"Original 1D Array (24 elements):\n{original}\n")

reshaped_2d = original.reshape(4, 6)
print(f"Reshaped to 4x6:\n{reshaped_2d}\n")

reshaped_3d = original.reshape(2, 3, 4)
print(f"Reshaped to 2x3x4:\n{reshaped_3d}\n")

flattened = reshaped_3d.flatten()
print(f"Flattened back to 1D:\n{flattened}\n")

transposed = reshaped_2d.T
print(f"Transposed (6x4):\n{transposed}\n")

# Reshape with -1 (auto-calculate dimension)
auto_reshape = original.reshape(6, -1)
print(f"Auto-reshaped (6, -1) → shape {auto_reshape.shape}:\n{auto_reshape}\n")

# 3.2 Broadcasting Techniques
print("\n3.2 Broadcasting Techniques:")
print("-" * 40)

# Example 1: Scalar broadcasting
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(f"Original Matrix:\n{matrix}\n")
print(f"Add scalar 10 (broadcasting):\n{matrix + 10}\n")